try to upload test results

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,14 +24,24 @@ jobs:
   # run test in the test file directory
   test:
     runs-on: ubuntu-latest
+    needs: [build] # why test if the build is broken
     steps:
       - name: Check out repo
         uses: actions/checkout@v4
 
       - name: Run Tests
-        run: |
+        run: | # the pipefail command lets me propogate a test failure through the output file pipe
+          set -o pipefail
           chmod +x test.sh
-          ./test.sh
+          ./test.sh | tee "test_${{github.run_id}}.log"
         shell: bash
+
+      - name: Upload Results
+        uses: actions/upload-artifact@v4
+        with:
+          name: test_${{github.run_id}}
+          path: test_${{github.run_id}}.log
+
+
       
     
